// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Wqp3vVn7HBe5x9Cp0DdF5NG2f5Qy0pA',
    appId: '1:114094659757:web:e9643b2d95ae0fb2978e24',
    messagingSenderId: '114094659757',
    projectId: 'finalproject-6c204',
    authDomain: 'finalproject-6c204.firebaseapp.com',
    databaseURL: 'https://finalproject-6c204-default-rtdb.firebaseio.com',
    storageBucket: 'finalproject-6c204.appspot.com',
    measurementId: 'G-GYW0FGC9EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjRGIHszFUyzKtSLBV7Xw7A7H9t_BzzMA',
    appId: '1:114094659757:android:1ad7bf4f1cdd8509978e24',
    messagingSenderId: '114094659757',
    projectId: 'finalproject-6c204',
    databaseURL: 'https://finalproject-6c204-default-rtdb.firebaseio.com',
    storageBucket: 'finalproject-6c204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-MD8Ma6nFFTax7QVdQWIHurCNoIHmkYI',
    appId: '1:114094659757:ios:6e8b8f070d32ffa9978e24',
    messagingSenderId: '114094659757',
    projectId: 'finalproject-6c204',
    databaseURL: 'https://finalproject-6c204-default-rtdb.firebaseio.com',
    storageBucket: 'finalproject-6c204.appspot.com',
    iosClientId: '114094659757-gfbgm3m36lvq335thl8k6grubl847ooo.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-MD8Ma6nFFTax7QVdQWIHurCNoIHmkYI',
    appId: '1:114094659757:ios:0bc34f66b74e7967978e24',
    messagingSenderId: '114094659757',
    projectId: 'finalproject-6c204',
    databaseURL: 'https://finalproject-6c204-default-rtdb.firebaseio.com',
    storageBucket: 'finalproject-6c204.appspot.com',
    iosClientId: '114094659757-d09tarqepljmhe4t88qm7p0j6j4vvi0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
